# Generated by Django 2.2.5 on 2021-06-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210619_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='house_rule',
            new_name='house_rules',
        ),
    ]
